### ISSUE TITLE
[Suggestions] Badge Numbers, Highlight and Sort By Recent Uploads

### ISSUE THREAD

**Issue by ghost** [Wassup789/YouTube-Notifications#10]
**[Badge numbers:](http://i.imgur.com/TMaCIVS.jpg)** Badge numbers will make it easier to see how many new uploads there are at a glance.

**Highlight and sort:** Channels are sorted alphabetically, instead of by recent uploads. Highlighting and sorting by the latest uploads will make it quicker to catch up on your subscriptions.

**Comment by Wassup789** [comment]
### Badge Numbers

Badge numbers were removed a couple versions ago due to the fact that my extension only looks for the latest video and not the videos before the video currently stored. I may implement the badge numbers in the future once I determine which method for counting badge numbers would be best if I plan on adding notifications for every missed video.

### Highlight and sort

Could you also elaborate what you mean by sort? The release version currently has three sorting functions by clicking on the dropdown menu on the top right. Also, I think sorting by release date would obviate the need for a highlighting function.

**Comment by ghost** [comment]
> The release version currently has three sorting functions by clicking on the dropdown menu on the top right.

My mistake, I didn't realize that the 3 dots in the corner had sorting options.

About the highlighting: the idea in mind was that new videos in the panel would be highlighted. Clicking on a highlighted video would mark it as watched, and un-highlight it.

Edit: I accidentally closed the issue.
