### ISSUE TITLE
Live Notifications Option

### ISSUE THREAD

**Issue by martokk** [Wassup789/YouTube-Notifications#21]
It would be great if you could add a feature to only show notifications when the user goes live. 

There are several channels that I would love to get a notification for when they go live, but don't want a notification when they upload a video. 

Thanks for this great extension!

**Comment by Wassup789** [comment]
Thanks, however in order to retrieve the live streams for a channel requires the user to be logged in to the extension using YouTube. Since the login token is only valid for a set amount of time, it would require the user to login multiple times. I may look into a workaround in the future, however my extension was flagged earlier for that as using an external endpoint is not allowed.

**Comment by DJQuadRocks** [comment]
Is this still the case? I'd love to see this feature as well!
