### ISSUE TITLE
Import Subscriptions Does nothing.

### ISSUE THREAD

**Issue by CrazyCrush3r** [Wassup789/YouTube-Notifications#30]
I click Import Subscriptions and it just takes me to youtube.com/feed/channels. Now what? How do I add them? And when I try to add them manually via the search bar, nothing happens at all. The search bar doesn't search for anything at all. No results at all.

**Comment by Classy-Cube** [comment]
I’m also having this issue, the Import Subscriptions had before opened a prompt seen in the gif. 
![test](https://user-images.githubusercontent.com/13388890/36070716-b9710b3a-0ece-11e8-8e9c-718c15cd2aec.GIF)
The developer hasn’t been active since November so until they fix this I’d recommend using Video Deck for YouTube.

**Comment by Classy-Cube** [comment]
To add channels click a channel’s bell button, unless you’ve enabled “Add buttons on YouTube” which adds a new button next to the subscribe button. Wassup789’s last update had added the “Synchronize with YouTube’s Bell” option and had made it default to being on. I believe he may have overlooked the new user experience since as you point out there is no obvious way of adding channels without knowing about the bell being the add channel button.

**Comment by Wassup789** [comment]
I have deprecated the import subscriptions feature in place of YouTube's notification bell instead. I should have made this clear in the update a few months back especially since the help page still shows the add buttons. You can still add channels by disabling the "Synchronize with YouTube's Bell" feature. May plan on updating the videos in the future.
